//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4016
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 
namespace CubeExercise {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    //[System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.fanrui.net/cubeexercise/2009/08/FormulasSchema.xsd")]
    [System.Xml.Serialization.XmlRootAttribute("Formulas", Namespace="http://schemas.fanrui.net/cubeexercise/2009/08/FormulasSchema.xsd", IsNullable=false)]
    public partial class Group {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Formula", typeof(Formula))]
        [System.Xml.Serialization.XmlElementAttribute("Group", typeof(Group))]
        public object[] Items;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool enabled;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool expanded;
        
        public Group() {
            this.enabled = true;
            this.expanded = true;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.fanrui.net/cubeexercise/2009/08/FormulasSchema.xsd")]
    public partial class Formula {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool enabled;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string image;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string script;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string preScript;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string postScript;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string demo;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(0)]
        public int practiceTimes;
        
        public Formula() {
            this.enabled = true;
            this.practiceTimes = 0;
        }
    }
}
